esphome:
  name: ${node_name}
  platform: ${node_platform}
  board: ${node_board}
  build_path: ./build/${node_name}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  reboot_timeout: 120min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${node_name}
    password: "abcd4321"

captive_portal:

# Enable logging
logger:
  level: ${log_level}

api:
  password: ${api_password}
  reboot_timeout: 1h

ota:
  password: ${ota_password}

# I²C Bus
i2c:
  sda: ${pin_sda}
  scl: ${pin_scl}
  scan: true
  frequency: 100kHz

sensor:
  - <<: !include ../sensor/uptime.yaml
  - <<: !include ../sensor/wifi_signal.yaml

binary_sensor:
#  - <<: !include shared/binary_sensor/connection_status.yaml

switch:
#  - !include shared/switch/restart_switch.yaml
