substitutions:
  node_name: bldc-fan-2
  node_friendly_name: "Fan 2"
  node_platform: ESP8266
  node_board: d1_mini
  i2c_scl: D1
  i2c_sda: D2
  <<: !include shared/base/secrets.yaml

packages:
  device_base: !include shared/base/device_base.yaml

i2c:
  scl: ${i2c_scl}
  sda: ${i2c_sda}

font:
  - file: "fonts/Eurosti.ttf"
    id: font1
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3c
    lambda: |-
      id(fan_animation).next_frame(); it.image(0, 0, id(fan_animation));
      it.print(0, 16, id(font1), "Call me esp8266!");

animation:
  - file: "shared/icon/fan_animation.gif"
    id: fan_animation

sensor:
  - <<: !include shared/sensor/uptime.yaml
  - <<: !include shared/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include shared/text_sensor/uptime_human.yaml

binary_sensor:
  - <<: !include shared/binary_sensor/connection_status.yaml

switch:
  - <<: !include shared/switch/restart_switch.yaml
