esphome:
  name: esp32-1
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0dabc1edfd99e7ab892b470ea6c15615"

wifi:
  ssid: "apollo"
  password: "chuotbodt"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-1 Fallback Hotspot"
    password: "MhbtT0UlmOWi"

captive_portal:

