esphome:
  name: esp32-1
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0dabc1edfd99e7ab892b470ea6c15615"

wifi:
  ssid: "apollo"
  password: "chuotbodt"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-1 Fallback Hotspot"
    password: "MhbtT0UlmOWi"

captive_portal:

font:
  - file: 'fonts/Eurosti.ttf'
    id: font1
    size: 8

spi:
  clk_pin: GPIO23
  mosi_pin: GPIO21

display:
  - platform: waveshare_epaper
    cs_pin: GPIO22
    dc_pin: GPIO19
    #busy_pin: D4
    #reset_pin: D5
    model: 2.90in
    full_update_every: 30
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");