substitutions:
  node_name: esp32
  node_friendly_name: "nodemcu32"
  node_platform: ESP32
  node_board: nodemcu-32s
  static_ip: 192.168.0.122
  i2c_sda: GPIO19
  i2c_scl: GPIO21
  <<: !include shared/base/secrets.yaml

packages:
  device_base: !include shared/base/device_base.yaml

font:
  - file: "fonts/Eurosti.ttf"
    id: font1
    size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3c
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");
